version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: medical_appointments_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - citas_network

volumes:
  mysql_data:
    driver: local

networks:
  citas_network:
    driver: bridge